# Server settings
maximum-islands: 100
islands-group: "islands"

# Generators
generators:
  enabled: true
  default: "overworld"

# Settings
default-settings:
  - CROPS_GROWTH
  - EGG_LAY
  - ENDERMAN_GRIEF
  - FIRE_SPREAD
  - GHAST_FIREBALL
  - LAVA_FLOW
  - PVP
  - TNT_EXPLOSION
  - TREE_GROWTH
  - WATER_FLOW
  - WITHER_EXPLOSION