always-day:
  material: SUNFLOWER
  name: "<green>Toujours le jour"
  lore:
    - "<gray>Garde l'île en plein jour."

always-middle-day:
  material: DAYLIGHT_DETECTOR
  name: "<green>Toujours midi"
  lore:
    - "<gray>Garde l'île à midi."

always-night:
  material: CLOCK
  name: "<green>Toujours la nuit"
  lore:
    - "<gray>Garde l'île de nuit."

always-middle-night:
  material: BLACK_BED
  name: "<green>Toujours minuit"
  lore:
    - "<gray>Garde l'île à minuit."

always-rain:
  material: WATER_BUCKET
  name: "<green>Toujours la pluie"
  lore:
    - "<gray>Fait toujours pleuvoir sur l'île."

always-shiny:
  material: GLOWSTONE
  name: "<green>Toujours beau temps"
  lore:
    - "<gray>Garde un ciel dégagé sur l'île."

creeper-explosion:
  material: CREEPER_HEAD
  name: "<green>Explosions de creepers"
  lore:
    - "<gray>Autorise les creepers à endommager l'île."

crops-growth:
  material: WHEAT
  name: "<green>Pousse des cultures"
  lore:
    - "<gray>Autorise les cultures à pousser sur l'île."

egg-lay:
  material: EGG
  name: "<green>Ponte des œufs"
  lore:
    - "<gray>Autorise les poules à pondre des œufs."

enderman-grief:
  material: ENDER_PEARL
  name: "<green>Endermen"
  lore:
    - "<gray>Autorise les endermen à prendre et déplacer des blocs."

fire-spread:
  material: FIRE_CHARGE
  name: "<green>Propagation du feu"
  lore:
    - "<gray>Autorise le feu à se propager sur l'île."

ghast-fireball:
  material: FIRE_CHARGE
  name: "<green>Boules de feu des ghasts"
  lore:
    - "<gray>Autorise les boules de feu des ghasts à endommager l'île."

lava-flow:
  material: LAVA_BUCKET
  name: "<green>Écoulement de la lave"
  lore:
    - "<gray>Autorise la lave à s'écouler sur l'île."

pvp:
  material: DIAMOND_SWORD
  name: "<green>PvP"
  lore:
    - "<gray>Autorise les joueurs à se battre sur l'île."

tnt-explosion:
  material: TNT
  name: "<green>Explosions de TNT"
  lore:
    - "<gray>Autorise la TNT, les cristaux de l'End, les lits"
    - "<gray>et les ancres de réapparition à endommager l'île."

tree-growth:
  material: OAK_SAPLING
  name: "<green>Pousse des arbres"
  lore:
    - "<gray>Autorise les pousses à devenir des arbres."

water-flow:
  material: WATER_BUCKET
  name: "<green>Écoulement de l'eau"
  lore:
    - "<gray>Autorise l'eau à s'écouler sur l'île."

wither-explosion:
  material: WITHER_SKELETON_SKULL
  name: "<green>Explosions du wither"
  lore:
    - "<gray>Autorise le wither à endommager l'île."
