always-day:
  material: SUNFLOWER
  name: "<green>Always Day"
  lore:
    - "<gray>Keeps the island time at day."

always-middle-day:
  material: DAYLIGHT_DETECTOR
  name: "<green>Always Midday"
  lore:
    - "<gray>Keeps the island time at midday."

always-night:
  material: CLOCK
  name: "<green>Always Night"
  lore:
    - "<gray>Keeps the island time at night."

always-middle-night:
  material: BLACK_BED
  name: "<green>Always Midnight"
  lore:
    - "<gray>Keeps the island time at midnight."

always-rain:
  material: WATER_BUCKET
  name: "<green>Always Rain"
  lore:
    - "<gray>Keeps the island weather rainy."

always-shiny:
  material: GLOWSTONE
  name: "<green>Always Shiny"
  lore:
    - "<gray>Keeps the island weather clear."

creeper-explosion:
  material: CREEPER_HEAD
  name: "<green>Creeper Explosion"
  lore:
    - "<gray>Allows creepers to damage the island."

crops-growth:
  material: WHEAT
  name: "<green>Crops Growth"
  lore:
    - "<gray>Allows crops to grow on the island."

egg-lay:
  material: EGG
  name: "<green>Egg Lay"
  lore:
    - "<gray>Allows chickens to lay eggs."

enderman-grief:
  material: ENDER_PEARL
  name: "<green>Enderman Grief"
  lore:
    - "<gray>Allows endermen to pick up and move blocks."

fire-spread:
  material: FIRE_CHARGE
  name: "<green>Fire Spread"
  lore:
    - "<gray>Allows fire to spread on the island."

ghast-fireball:
  material: FIRE_CHARGE
  name: "<green>Ghast Fireball"
  lore:
    - "<gray>Allows ghast fireballs to damage the island."

lava-flow:
  material: LAVA_BUCKET
  name: "<green>Lava Flow"
  lore:
    - "<gray>Allows lava to flow on the island."

pvp:
  material: DIAMOND_SWORD
  name: "<green>PvP"
  lore:
    - "<gray>Allows players to fight on the island."

tnt-explosion:
  material: TNT
  name: "<green>TNT Explosion"
  lore:
    - "<gray>Allows TNT to damage the island."

tree-growth:
  material: OAK_SAPLING
  name: "<green>Tree Growth"
  lore:
    - "<gray>Allows saplings to grow into trees."

water-flow:
  material: WATER_BUCKET
  name: "<green>Water Flow"
  lore:
    - "<gray>Allows water to flow on the island."

wither-explosion:
  material: WITHER_SKELETON_SKULL
  name: "<green>Wither Explosion"
  lore:
    - "<gray>Allows the wither to damage the island."
